; specify the configuration here 
IniRead, everythingPath, .\config.ini, tools, everythingPath
IniRead, virtualMachineManager, .\config.ini, tools, virtualMachineManager
IniRead, processExplorer, .\config.ini, tools, processExplorer
IniRead, desktopFolder, .\config.ini, tools, desktopFolder
IniRead, gifTool, .\config.ini, tools, gifTool
IniRead, searchEngine, .\config.ini, tools, searchEngine
IniRead, searchEngineAlt, .\config.ini, tools, searchEngineAlt
IniRead, editor, .\config.ini, tools, editor
IniRead, cmd, .\config.ini, tools, cmd
