; specify the configuration here 
IniRead, everythingPath, .\config.ini, tools, everythingPath
IniRead, virtualMachineManager, .\config.ini, tools, virtualMachineManager
IniRead, processExplorer, .\config.ini, tools, processExplorer
IniRead, gifTool, .\config.ini, tools, gifTool
IniRead, searchEngine, .\config.ini, tools, searchEngine
IniRead, searchEngineSecondary, .\config.ini, tools, searchEngineSecondary
IniRead, editor, .\config.ini, tools, editor
IniRead, code, .\config.ini, tools, code
IniRead, cmd, .\config.ini, tools, cmd
IniRead, ruler, .\config.ini, tools, ruler
IniRead, visualStudio, .\config.ini, tools, visualStudio
